# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MrinjamulCli < Formula
  desc "A CLI to sync domains from local to Cloudflare."
  homepage "https://github.com/linuxuserin/go-github"
  version "1.1.1-beta"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.1-beta/mrinjamul-cli_1.1.1-beta_darwin_amd64.tar.gz"
      sha256 "95657a85c517a743e71e69fddca50d6c4a206640a76d97f76b7d374463969e6b"

      def install
        bin.install "mrinjamul-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.1-beta/mrinjamul-cli_1.1.1-beta_darwin_arm64.tar.gz"
      sha256 "645fc6dc407ed0c4522fa0d7b98bea7ce93448d6b07f94c3d6573275566d0c5e"

      def install
        bin.install "mrinjamul-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.1-beta/mrinjamul-cli_1.1.1-beta_linux_amd64.tar.gz"
      sha256 "37924cce034fd2af280bd9c90c5e7aa081da0f366f73d333c80dcc6a0b4dbc64"

      def install
        bin.install "mrinjamul-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.1-beta/mrinjamul-cli_1.1.1-beta_linux_arm64.tar.gz"
      sha256 "68d27de58e508f64a6edc3aced6946869dc32d0c51c41c89163d0515e21e2918"

      def install
        bin.install "mrinjamul-cli"
      end
    end
  end
end
