# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MrinjamulCli < Formula
  desc "A CLI to sync domains from local to Cloudflare."
  homepage "https://mrinjamul.github.io/mrinjamul-cli"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.2/mrinjamul-cli_1.1.2_darwin_amd64.tar.gz"
      sha256 "a2004e8e0b874d859957a80f83e17a4e44a10ff8633827a562ec3251a59f5d3f"

      def install
        bin.install "mrinjamul-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.2/mrinjamul-cli_1.1.2_darwin_arm64.tar.gz"
      sha256 "bfc65983c3b42f2eb4644f22ab6382a61a1f3052978246ac5d6ebb5376e4db29"

      def install
        bin.install "mrinjamul-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.2/mrinjamul-cli_1.1.2_linux_amd64.tar.gz"
      sha256 "888caae769bd35c2bb7d40ae6daca83fb6e27ac6f4ad5817ce1b28ec8d65da95"

      def install
        bin.install "mrinjamul-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/mrinjamul-cli/releases/download/v1.1.2/mrinjamul-cli_1.1.2_linux_arm64.tar.gz"
      sha256 "0b0e3d7d0bdd38eac91183105afec87b42890fb71505b3b0a477c8d959157c2f"

      def install
        bin.install "mrinjamul-cli"
      end
    end
  end
end
