# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sws < Formula
  desc "A simple (static) web server written in golang"
  homepage "https://github.com/mrinjamul/simple-web-server"
  version "1.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.1.3/simple-web-server_1.1.3_darwin_amd64.tar.gz"
      sha256 "3059977a42ac000e988d1a7ed2e3aeba854a37734883955c283c8a2d03cd76e8"

      def install
        bin.install "sws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.1.3/simple-web-server_1.1.3_darwin_arm64.tar.gz"
      sha256 "30ca413fa8abb7f1f216ace6184b8daf553b7f04703dec299cbfd81552f04585"

      def install
        bin.install "sws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.1.3/simple-web-server_1.1.3_linux_arm64.tar.gz"
      sha256 "1830ca567aa7fc36269c2174696901814ed1aec8edfb9fef6afdbc73e1c45a6c"

      def install
        bin.install "sws"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.1.3/simple-web-server_1.1.3_linux_amd64.tar.gz"
      sha256 "c5ccc609a05423bf809f6b43cdbff68ead130886a05a250c9cc464a1b49b06cf"

      def install
        bin.install "sws"
      end
    end
  end
end
