# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sws < Formula
  desc "A simple (static) web server written in golang"
  homepage "https://github.com/mrinjamul/simple-web-server"
  version "1.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_darwin_amd64.tar.gz"
      sha256 "28d9ad0b6b847929427c7a331ee13bf819109811c4f98484bf7219adeac19187"

      def install
        bin.install "sws"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_darwin_arm64.tar.gz"
      sha256 "f9b2076132bca9d2110a751b010683bc7734a19917ad309430031b307242ad9a"

      def install
        bin.install "sws"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_linux_arm64.tar.gz"
      sha256 "1fe84c7a7225b7b5abfcced1bd1822fe07575075079ce7f412d4188ec49f32f0"

      def install
        bin.install "sws"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/simple-web-server/releases/download/v1.2.0/simple-web-server_1.2.0_linux_amd64.tar.gz"
      sha256 "2c1f4513f1fcb008877c520db100a8818588157c59c714faed296c80f09e5756"

      def install
        bin.install "sws"
      end
    end
  end
end
