# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tasks < Formula
  desc "A simple todoist application"
  homepage "https://github.com/mrinjamul/tasks"
  version "1.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.0/tasks_1.1.0_darwin_amd64.tar.gz"
      sha256 "53e0e7c08d4636885fac51a960250fb0b39b88b9c6d688776b1d31e284feed88"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.0/tasks_1.1.0_darwin_arm64.tar.gz"
      sha256 "663afd4a1e44826241493e28bf0ee90d7e76d06160031dfce0bc0a8684f6d6b6"

      def install
        bin.install "tasks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.0/tasks_1.1.0_linux_amd64.tar.gz"
      sha256 "1ecd39dde436490548893e35f14a838eded11d3334ed6781e3cc2b954bdb9641"

      def install
        bin.install "tasks"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrinjamul/tasks/releases/download/v1.1.0/tasks_1.1.0_linux_arm64.tar.gz"
      sha256 "d4b4fc0d8efa98d8866eb27319115205fc36a0797ce484211e9d6aa8c04f875d"

      def install
        bin.install "tasks"
      end
    end
  end
end
